In [2]:
import pandas as pd
ages_over_300df1=pd.read_csv('/Users/lihan/Downloads/EarlyDRGPrediction-main/data/ms/drg_cohort.csv')
df2=pd.read_csv('/Users/lihan/Downloads/PATIENTS.csv')
ids_in_df2 = df1['SUBJECT_ID'].isin(df2['SUBJECT_ID'])

In [4]:
if (ids_in_df2 == False).any():
    print("There are IDs from df1 not found in df2!")
else:
    print("All IDs from df1 are found in df2!")


All IDs from df1 are found in df2!


In [26]:
ages_over_300 = df1[df1['AGE'] >90]['AGE']
ages_over_300 = ages_over_300[ages_over_300 <100]
ages_over_300



Series([], Name: AGE, dtype: float64)

In [13]:
if (ids_in_df2 == True).all():
    print(1)

1


In [48]:
import numpy as np
import torch.nn as nn
import torch
age=torch.tensor([[10],[15]])

lstm_out=torch.tensor([[10,11],[10,11]])
age_embedding = nn.Embedding(16, 2)  # 假设年龄从0到99
age_embed=age_embedding(age).squeeze(1)
print(age_embed)
combined = torch.cat([lstm_out, age_embed], dim=1)
combined

tensor([[-0.3051, -1.3395],
        [ 0.2074, -0.4451]], grad_fn=<SqueezeBackward1>)


tensor([[10.0000, 11.0000, -0.3051, -1.3395],
        [10.0000, 11.0000,  0.2074, -0.4451]], grad_fn=<CatBackward0>)

In [56]:
import torch

# Max-pooling based downsample method
def max_pooling_downsample(tensor, threshold=6, target_length=4):
    B, T, N = tensor.size()
    real_lengths = (tensor.sum(dim=-1) != 0).sum(dim=-1)

    # If sequence length exceeds the threshold
    if T > threshold:
        # Calculate kernel size and stride for unfolding
        kernel_size = int(T / (T / target_length + 1))
        stride = int(T / target_length)
        
        # Unfold and apply max pooling
        unfolded = tensor.unfold(1, kernel_size, stride)
        pooled, _ = unfolded.max(2)
        return pooled
    else:
        return tensor[:, :target_length, :]

# Create a tensor of shape (10, 2000, 5) with random values

batch_data = []

for i in range(4, 6, 1):
    actual_data = torch.rand((1, i, 5))
    padding = torch.zeros((1, 9-i, 5))
    batch_data.append(torch.cat([actual_data, padding], dim=1))
batch_tensor = torch.cat(batch_data, dim=0)

# Apply the downsample method
processed_tensor = max_pooling_downsample(batch_tensor)

print(processed_tensor.shape)  # Expected: torch.Size([10, 1000, 5])


torch.Size([2, 4, 2])


In [59]:

# kernel_size = int(T / (T / target_length + 1))
# print(kernel_size)
print(batch_tensor)
B, T, N = batch_tensor.size()
real_lengths = (batch_tensor.sum(dim=-1) != 0).sum(dim=-1)

print(real_lengths)
processed_tensor

tensor([[[0.1822, 0.8718, 0.2795, 0.1798, 0.7891],
         [0.1257, 0.9804, 0.8325, 0.6862, 0.3280],
         [0.5368, 0.0409, 0.1606, 0.3597, 0.5543],
         [0.2861, 0.3673, 0.4645, 0.2441, 0.0097],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.3657, 0.2430, 0.7294, 0.3794, 0.6483],
         [0.0430, 0.1990, 0.0665, 0.5897, 0.8054],
         [0.6253, 0.5174, 0.1494, 0.0919, 0.1542],
         [0.5632, 0.3947, 0.2653, 0.4783, 0.8072],
         [0.7216, 0.8522, 0.8390, 0.6409, 0.2075],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]])
tensor([4, 5])


tensor([[[0.8718, 0.9804],
         [0.5543, 0.4645],
         [0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.7294, 0.8054],
         [0.6253, 0.8072],
         [0.8522, 0.0000],
         [0.0000, 0.0000]]])

In [51]:
batch_data = []

for i in range(500, 2001, 150):
    actual_data = torch.rand((1, i, 5))
    padding = torch.zeros((1, 2000-i, 5))
    batch_data.append(torch.cat([actual_data, padding], dim=1))
batch_tensor = torch.cat(batch_data, dim=0)
batch_tensor

tensor([[[0.1821, 0.9440, 0.2735, 0.2607, 0.7291],
         [0.9347, 0.0265, 0.2630, 0.7769, 0.1766],
         [0.5705, 0.1265, 0.8474, 0.8550, 0.0121],
         ...,
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.2370, 0.5597, 0.4324, 0.4698, 0.9455],
         [0.9824, 0.3785, 0.3324, 0.2648, 0.6795],
         [0.5968, 0.4217, 0.3375, 0.0432, 0.0230],
         ...,
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.7060, 0.1280, 0.0939, 0.5104, 0.4572],
         [0.5030, 0.2368, 0.9488, 0.7287, 0.1911],
         [0.7799, 0.1279, 0.6501, 0.8544, 0.1421],
         ...,
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        ...,

        [[0.0483, 0.

In [5]:
import torch

# Max-pooling based downsample method
def max_pooling_downsample(tensor, threshold=6, target_length=4):
    B, T, N = tensor.size()
    print(N)
    # Detect the actual length of the sequence based on non-zero values
    real_lengths = (tensor.sum(dim=-1) != 0).sum(dim=-1)
    lx=real_lengths
    # print(real_lengths)
    # Initialize a container for processed data
    processed_list = []
    
    for i in range(B):
        # If the real length exceeds the threshold
        if real_lengths[i] > threshold:
            actual_tensor = tensor[i, :real_lengths[i], :]
            lx[i]=lx[i]//2
            print(actual_tensor.size())
            kernel_size = 2
            # print(kernel_size)
            stride = 2
            unfolded = actual_tensor.unfold(0, kernel_size, stride)
            unfolded=unfolded.transpose(1,2)

            # print(stride)
            print(unfolded.size())
            pooled, _ = unfolded.max(1)

            print(pooled)
            # padding to target length
            if pooled.size(0) < target_length:
                padding_size = target_length - pooled.size(0)
                padding = torch.zeros(padding_size, pooled.size(1), device=tensor.device)  # Adjust the creation of the padding tensor
                print(padding.size())
                pooled = torch.cat([pooled, padding], dim=0)
            
            processed_list.append(pooled)
            # toDown=actual_tensor[]
        elif real_lengths[i] <= threshold and real_lengths[i]>target_length:
            lx[i]=target_length
            processed_list.append(tensor[i, :target_length, :])
        else:
            processed_list.append(tensor[i, :target_length, :])
           
    return torch.stack(processed_list),lx

# Example: Create a tensor of shape (10, 2000, 5)
# With different "real" lengths (ranging from 500 to 2000)
batch_data = []
for i in range(2, 9, 1):
    actual_data = torch.rand((1, i, 5))
    padding = torch.zeros((1, 9-i, 5))
    batch_data.append(torch.cat([actual_data, padding], dim=1))
batch_tensor = torch.cat(batch_data, dim=0)
print(batch_tensor)
# Apply the downsample method
processed_tensor ,lx= max_pooling_downsample(batch_tensor)

print(processed_tensor)  # Expected: torch.Size([10, 1000, 5])
print(lx)

tensor([[[0.5080, 0.8517, 0.9346, 0.0901, 0.5518],
         [0.9521, 0.0379, 0.4136, 0.5263, 0.2782],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.0412, 0.9818, 0.8709, 0.1050, 0.9679],
         [0.2897, 0.0995, 0.2709, 0.5828, 0.0580],
         [0.7747, 0.6732, 0.7475, 0.8872, 0.7089],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.7677, 0.6451, 0.2500, 0.9647, 0.6870],
         [0.9794, 0.4828, 0

In [ ]:
raw=torch.rand((6,5))
print(raw)
kernel=2
stride=2
unfolded = raw.unfold(0, kernel, stride)
print(unfolded.size())
unfolded=unfolded.transpose(1,2)
pooled, _ = unfolded.max(1)

print(unfolded)
pooled

In [34]:
import torch

# Max-pooling based downsample method
def max_pooling_downsample(tensor, threshold=6, target_length=4):
    B, T, N = tensor.size()
    print(N)
    # Detect the actual length of the sequence based on non-zero values
    real_lengths = (tensor.sum(dim=-1) != 0).sum(dim=-1)
    lx=real_lengths
    # print(real_lengths)
    # Initialize a container for processed data
    processed_list = []
    # print(tensor)
    for i in range(B):
        # print('rea',real_lengths[i])
        real_length=real_lengths[i]
        tmp=real_length
        # If the real length exceeds the threshold
        if real_lengths[i] > target_length:
            # print('rea1',real_lengths[i])
            real_length=real_lengths[i]
            tmp=real_length
            to_down_l=(real_length-target_length)*2
            toDown_tensor = tensor[i, :to_down_l, :]
            
            # print(actual_tensor.size())
            kernel_size = 2
            # print(kernel_size)
            stride = 2
            unfolded = toDown_tensor.unfold(0, kernel_size, stride)
            unfolded=unfolded.transpose(1,2)
            # print('rea2',tmp)
            # print(stride)
            # print(unfolded.size())
            pooled, _ = unfolded.max(1)
            # print(i)
            # print('pool',pooled)
            # padding to target length
            
                # left_length = real_lengths[i] - target_length
            # print('tdl',to_down_l)
            # print('r+1',real_length+1)
            left = tensor[i, to_down_l:real_length, :]  # Adjust the creation of the padding tensor
            # print('left',left)
            pooled = torch.cat([pooled, left], dim=0)
            # print(pooled.size())
            processed_list.append(pooled)
            # toDown=actual_tensor[]
            lx[i]=target_length
        else:

            processed_list.append(tensor[i, :target_length, :])
           
    return torch.stack(processed_list),lx

# Example: Create a tensor of shape (10, 2000, 5)
# With different "real" lengths (ranging from 500 to 2000)
batch_data = []
for i in range(2, 9, 1):
    actual_data = torch.rand((1, i, 5))
    padding = torch.zeros((1, 9-i, 5))
    batch_data.append(torch.cat([actual_data, padding], dim=1))
batch_tensor = torch.cat(batch_data, dim=0)
print(batch_tensor)
# Apply the downsample method
processed_tensor ,lx= max_pooling_downsample(batch_tensor)

print(processed_tensor)  # Expected: torch.Size([10, 1000, 5])
print(lx)

tensor([[[0.6496, 0.1434, 0.1448, 0.9938, 0.5371],
         [0.3639, 0.4431, 0.9548, 0.9542, 0.4542],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.7717, 0.4986, 0.2477, 0.0887, 0.9200],
         [0.5334, 0.4013, 0.4973, 0.0635, 0.2040],
         [0.6481, 0.8217, 0.8711, 0.0922, 0.1742],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.5429, 0.1281, 0.4630, 0.3449, 0.8002],
         [0.1014, 0.4587, 0